package nz.ac.auckland.se281;

/** Interface implements the Strategy (Top or Random) for the Ai fingers. */
public interface Strategy {

  /**
   * This method is used to generate the Ai fingers depending on the strategy used.
   *
   * @return integer value of fingers between 0 and 5 inclusive generated by specific strategy.
   */
  int aiStrategy();
}
